[build]
  command = "npm install --legacy-peer-deps && npm install @babel/plugin-proposal-private-property-in-object --save-dev --legacy-peer-deps && npm run build --legacy-peer-deps"
  publish = "client/build"